name: login_page
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Dil desteği için 
    sdk: flutter
  intl: any              # Tarih/Saat formatları ve çeviri altyapısı
  provider: ^6.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
