name: login_page
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  firebase_storage: ^13.0.5
  rxdart: ^0.28.0
  connectivity_plus: ^6.1.4
  google_maps_flutter: ^2.14.0
  geolocator: ^10.1.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_local_notifications: ^18.0.1
  qr_flutter: ^4.1.0
  timezone: ^0.10.0
  package_info_plus: ^8.1.2
  audioplayers: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/mavikalitelilogo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/mavikalitelilogo_arkaplanyok.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/avatars/
    - assets/sounds/
